tap "felixkratz/formulae"
tap "homebrew/bundle"
tap "homebrew/services"
tap "shaunsingh/sfmono-nerd-font-ligaturized"
#brew "ansible"
#brew "highway"
brew "eza"
#brew "fish"
#brew "fzf"
#brew "git-delta"
#brew "gitversion"
#brew "gnupg"
#brew "hopenpgp-tools"
#brew "htop"
#brew "ifstat"
#brew "jq"
#brew "openjdk"
#brew "ktlint"
#brew "lazygit"
#brew "lftp"
#brew "libavif"
#brew "lsusb"
brew "lua"
brew "luarocks"
#brew "mas"
#brew "maven"
#brew "ninja"
#brew "nmap"
#brew "node"
#brew "nowplaying-cli"
#brew "pango"
#brew "pinentry-mac"
#brew "python@3.11"
#brew "qt@5"
#brew "ranger"
#brew "rbenv"
#brew "rclone"
brew "rcm"
#brew "restic"
#brew "sevenzip"
#brew "starship"
#brew "switchaudio-osx"
#brew "telnet"
#brew "tree"
#brew "unar"
#brew "vim"
#brew "wget"
#brew "xcbeautify"
#brew "ykman"
#brew "ykpers"
#brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar"
cask "aerospace"
#cask "aldente"
#cask "alt-tab"
#cask "android-commandlinetools"
#cask "android-platform-tools"
#cask "autodesk-fusion"
#cask "bettertouchtool"
#cask "discord"
#cask "element"
#cask "font-fira-code"
#cask "font-fira-code-nerd-font"
#cask "font-hack-nerd-font"
cask "font-sf-mono"
cask "font-sf-mono-nerd-font-ligaturized"
cask "font-sf-pro"
#cask "gimp"
#cask "inkscape"
#cask "kitty"
#cask "logi-options+"
#cask "middleclick"
#cask "monitorcontrol"
#cask "moonlight"
#cask "notchnook"
#cask "notunes"
#cask "osxfuse"
#cask "proxy-audio-device"
#cask "prusaslicer"
#cask "qlcolorcode"
#cask "qlmarkdown"
#cask "qlprettypatch"
#cask "qlstephen"
#cask "quassel"
#cask "quicklook-csv"
#cask "quicklook-json"
#cask "raycast"
cask "sf-symbols"
#cask "shortcat"
#cask "signal@beta"
#cask "slack"
cask "spotify"
#cask "steam"
#cask "suspicious-package"
#cask "the-unarchiver"
cask "visual-studio-code"
#cask "vlc"
#cask "webpquicklook"
#cask "yubico-yubikey-manager"
#mas "Amphetamine", id: 937984704
#mas "AusweisApp", id: 948660805
#mas "Bitwarden", id: 1352778147
#mas "Color Picker", id: 1545870783
#mas "Command X", id: 6448461551
#mas "GarageBand", id: 682658836
#mas "iMovie", id: 408981434
#mas "Infuse", id: 1136220934
#mas "Keynote", id: 409183694
#mas "Numbers", id: 409203825
#mas "Pages", id: 409201541
#mas "Pure Paste", id: 1611378436
#mas "Quick Camera", id: 598853070
#mas "Steam Link", id: 1246969117
#mas "Windows App", id: 1295203466
#mas "WireGuard", id: 1451685025
#mas "Xcode", id: 497799835
#vscode "ms-python.debugpy"
#vscode "ms-python.python"
#vscode "ms-python.vscode-pylance"
#vscode "ms-toolsai.jupyter"
#vscode "ms-toolsai.jupyter-keymap"
#vscode "ms-toolsai.jupyter-renderers"
#vscode "ms-toolsai.vscode-jupyter-cell-tags"
#vscode "ms-toolsai.vscode-jupyter-slideshow"
#vscode "ms-vscode-remote.remote-ssh"
#vscode "ms-vscode-remote.remote-ssh-edit"
#vscode "ms-vscode.remote-explorer"
#vscode "shd101wyy.markdown-preview-enhanced"
#vscode "tamasfe.even-better-toml"
#vscode "yy0931.vscode-sqlite3-editor"
